### PR TITLE
mdenise Practice0

### PR DESCRIPTION
**Pull request by marydenise**

### CODE REVIEW

**Review by robobenklein — CHANGES_REQUESTED** [review]
Don't delete the original file!

**Comment by marydenise** [comment]
how should I restore the original file?

**Comment by robobenklein** [comment]
You should avoid committing changes to it, now you'll probably want to either amend your commits, or just make a new branch and checkout your own notebook file from this branch.

**Comment by marydenise** [comment]
what commands should I use to make the new branch and checkout my notebook file? Would it be like
git checkout Practice0
git checkout -b newbranch Practice0

**Comment by marydenise** [comment]
let me know if this worked

**Review by robobenklein — CHANGES_REQUESTED** [review]
You've still gotta avoid changing the original Practice file!

Be sure when you create a new branch, do it from a commit in history before you've made any modifications!

**Comment by marydenise** [comment]
what do you mean do it from a commit in history before

**Comment by robobenklein** [comment]
When you create a new branch, you can choose the point it branches from, in this case you could branch from any commit between 9772875fcab16d19858f7551ffc71ba414452539 and the most recent version on *this repo's* master branch.

`git branch branch_name <commit-ish>`

With your new branch, checkout *only* your notebook file: `git checkout branch_name filename`

**Comment by marydenise** [comment]
okay I tried those commands, I hope that worked.

**Comment by robobenklein** [comment]
Still not there yet, look at the 'Files changed' tab of the PR to check for yourself. So long as there are any other files modified besides your own notebook file, it's not quite right.

**Comment by marydenise** [comment]
okay, I'm trying 9772875 for the commit-ish and following it with git checkout newbranch mdenise.ipynb and it returns:
error: pathspec 'mdenise.ipynb' did not match any file(s) known to git

**Comment by robobenklein** [comment]
I could've been clearer there:

`git checkout existing_branch filename` gets `filename` from `existing_branch`. Your new one doesn't have those changes (which is correct), so you want to checkout from your old one, in this case it looks like `master` on your repo.

**Comment by marydenise** [comment]
did git checkout master mdenise.ipynb then add and commit

**Comment by marydenise** [comment]
I am so lost. I used the early commit-ish 9772875 and only used checkout on mdenise, but its still changing Practice0 in the files changed tab

**Comment by robobenklein** [comment]
This PR merges from your master to the class's master, you made a new branch so you'll either need to change this PR's base branch or open a new PR.

**Comment by marydenise** [comment]
would I change the base branch to the newbranch created?

**Comment by robobenklein** [comment]
Not sure if GitHub supports this here, might be easier to just make a new PR from your new branch.

**Comment by marydenise** [comment]
okay should i go ahead and close this one?

**Pull request closed without merging**
