### PR TITLE
Finished Practice0

### PR DESCRIPTION
**Pull request by tristan-ainley**

### CODE REVIEW

**Review by robobenklein — CHANGES_REQUESTED** [review]
Don't change the other files!

**Comment by tristan-ainley** [comment]
I'm having an issue connecting to my localhost:8888 now and I have no idea why. I did the exact same thing and now I get this error below. Any ideas as to what's wrong?
Connection refused
:

**Comment by robobenklein** [comment]
You shut down your notebook, it can't connect because your notebook server isn't running anymore.

You can restart it with `bash /bin/notebook.sh`

**Comment by tristan-ainley** [comment]
Reverted the previous commit and just added the tainley.ipynb. Thank you for the help! I would have never discovered that on my own.

**Review by robobenklein — APPROVED** [review]

**Pull request merged**
