### PR TITLE
finish practice0

### PR DESCRIPTION
**Pull request by NehPatel2000**

### CODE REVIEW

**Comment by robobenklein** [comment]
Any reason you want us to review this?

**Comment by NehPatel2000** [comment]
> Any reason you want us to review this?

Just assumed this was the protocol, are we just supposed to make the pr with no reviewers?

**Comment by robobenklein** [comment]
The CODEOWNERS file is automatically requesting and requiring reviews when someone touches the original practice file, which they aren't supposed to do.

**Comment by NehPatel2000** [comment]
I see thank you

**Review by robobenklein — APPROVED** [review]

**Pull request merged**
