### PR TITLE
create friya.ipynb

### PR DESCRIPTION
**Pull request by friya15**

### CODE REVIEW

**Review by robobenklein — CHANGES_REQUESTED** [review]
why changing practice file?

**Comment by friya15** [comment]
My previous pull request was not accepted so I deleted the old fork to
create a new one and uploaded the task again.

**Comment by robobenklein** [comment]
Why delete the fork? You're supposed to add your new file, and avoid committing any changes to the original.

Look under the 'Files Changed' tab, you should only see your own netid.ipynb there.

**Comment by friya15** [comment]
I hope I fixed it now. Could you please check it this time. I apologize for
the mistake.

**Comment by robobenklein** [comment]
Still not quite there, I suggest to make a new branch without these commits and just commit only your netid.ipynb file.

Remember to look at the 'Commits' and 'Files Changed' tab, if *any* commit modifies Practice0, then it's not right.

**Pull request closed without merging**
