### PR TITLE
Practice0

### PR DESCRIPTION
**Pull request by kammerdienerb**

### CODE REVIEW

**Review by robobenklein — CHANGES_REQUESTED** [review]
Don't delete the practice file!

**Comment by kammerdienerb** [comment]
Okay, I've restored the file. It is confusing that the wording on the "news" page says:
> rename the notebook on your container

**Comment by robobenklein** [comment]
Sure, you can rename it, but then you missed the other bit of instructions that shows how you should only add/stage and commit changes to your own file.

**Comment by kammerdienerb** [comment]
Ah, I see. My bad.

**Review by robobenklein — CHANGES_REQUESTED** [review]
You've still got commits that change the practice file, you'll either want to make a new branch and checkout your file onto that (and make a new PR from the clean, new branch) or interactive rebase to get rid of the offending commits.

**Pull request closed without merging**
